### ISSUE TITLE
Add paragraph on near-term potential of blockchain technologies for space for near-Earth, on-orbit applications

### ISSUE THREAD

**Issue by bretthenderson** [prototypo/blockchains-in-space#4]
**Reviewer 1 Comment**
In section 3A, Near-Planetary Economies, spacecraft with autonomy and intelligent systems on board will likely be incentivized to compete with other spacecraft to efficiently accomplish both routine and time sensitive, pop-up tasks, such as detecting and providing the precise location of a downed aircraft or providing time-sensitive imagery in a specific wavelength of an in-progress event.  This is an example (not yet covered in this paper) of a near-Earth, on-orbit economy that could make practical use of blockchain for economic purposes and only needs the “read-only” and “write request” capabilities. Consider explicitly adding these (or similar) additional examples to drive home the near-term potential of blockchain technologies for space.

**Comment by saltiniroberto** [comment]
I have assigned this to David based on my understanding from a conversation that I had with him today.
@prototypo , please feel free to unassign yourself if my understanding of our conversation was incorrect.

**Comment by prototypo** [comment]
Yes, I think I have this one. I'm working on an extension of Mandl's concept to use as the answer to both this one and https://github.com/prototypo/blockchains-in-space/issues/5

**Comment by prototypo** [comment]
I believe the proposal for #5 has covered this one as well. I'm going to close it. Please feel free to reopen it if anyone disagrees.
