### ISSUE TITLE
Extend Mandl’s concept (mentioned in the paper) of coordination between satellites to fulfill imaging requests

### ISSUE THREAD

**Issue by bretthenderson** [prototypo/blockchains-in-space#5]
**Reviewer 2 Comment**
it is unclear to this reviewer if the manuscript in its current form should be a full paper or a note or a survey paper. To deserve publication as a full research paper, I would recommend extending the paper to include a case study or at least a detailed running example that would serve to illustrate the motivation and some of the main concepts in the paper, and help substantiate some of the claims made in the paper. 

Right now, the paper feels a bit shallow. Several claims that are important to the arguments made in the paper (e.g., blockchains are useful for space, certain roles are more relevant than others, certain consensus algorithms are not applicable, etc.) are made without much justification or discussion. If there was such case study or running example, it would help emphasize the relevance for space and substantiate some of those claims. 

**David Hyland-Wood Coment**
Mandl suggested decentralised coordination of a small number of satellites. We could easily tell a story of a competitive economy based on the same model and use it as a thread through the document.

**Comment by prototypo** [comment]
Part of Reviewer 2's confusion may have been statements such as:
> This paper **reviews** extant blockchain properties that could be used to construct future in-space economies.

I have changed such statements to make clear we are not writing a review paper, but instead making a contribution:
> This paper **suggests** extant blockchain properties that could be used to construct future in-space economies.

**Comment by prototypo** [comment]
Working on extending Mandl's idea into a thread through the paper now.

**Comment by prototypo** [comment]
Proposal to answer this concern at https://github.com/prototypo/blockchains-in-space/commit/ee6026dac90d96aacd9677c271c240ada79a2a73

**Comment by prototypo** [comment]
Closing this issue as resolved following positive reviews by @saltiniroberto and @drinkcoffee

**Comment by bretthenderson** [comment]
Looks good @prototypo. One minor change to the following sentence on Page 10

> Challenges to the traditional dominance of geosynchronous satellites in the telecommunications market by LEO and MEO competitors may allow both the geosynchronous orbit and mature spacecraft designs **to be used such other purposes**.

The part highlighted seems to be missing a "for"
