### ISSUE TITLE
Highlight what we don’t currently know about blockhains for space applications, and how this paper addresses those knowledge gaps

### ISSUE THREAD

**Issue by bretthenderson** [prototypo/blockchains-in-space#6]
**Reviewer 2 Comment**
Part of the reason why the paper felt like a note or a survey is that it does not really emphasize the typical hypothesis- or research-question-driven flow of a scientific paper. For example, the literature review is very thorough but it doesn’t make a good job of highlighting what we don’t currently know about blockhains for space applications, and how this paper addresses those knowledge gaps.

**Comment by bretthenderson** [comment]
**David Hyland-Wood Comment**

I think we can quickly address the latter point (about highlighting what we don't know) with a sentence in the Abstract, a paragraph in the literature review, and a sentence in the Conclusions. Something like:  

**Abstract**
We briefly identify known gaps in our knowledge regarding the application of blockchains to space applications.

 **Literature Review**
We currently don't have a good appreciation for the amount of time, power, and heat rejection required to run blockchain wallets, validators, exchanges or light clients on the computational systems of current or near-future spacecraft. No such material was found by us in published literature. It would be helpful to conduct such a study to validate some of the assumptions discussed later in this paper.

 **Conclusion**
Known gaps in our knowledge of blockchain applicability were highlighted in the literature review.

**Comment by saltiniroberto** [comment]
@prototypo 
I have pushed some text here
https://github.com/prototypo/blockchains-in-space/tree/research-question/Journal%20of%20Aerospace%20Information%20Systems/Blockchain%20Properties%20for%20Near-Planetary%2C%20Interplanetary%20and%20Metaplanetary%20Space%20Domains

I have also added a few missing hyphenations that were causing some box overfull warnings and added a couple of missing full stops.
I used todo notes to highlight the changes.

**Note: I have not pushed the complied PDF to make it easier to merge the changes. So, you need to compile the current tex to get the todo notes and the changes printed to PDF**

**Comment by saltiniroberto** [comment]
I have not created  PR for this as I am not sure that this as I don't think that it is necessarily the best way given that PRs are usually supposed to be eventually merged into the master but merging tex files is quite harder when you have more than one sentence per line.

**Comment by prototypo** [comment]
Thanks, @saltiniroberto. I will integrate your work with mine directly since there is a bit of overlap.

**Comment by prototypo** [comment]
Added https://github.com/prototypo/blockchains-in-space/commit/2de98e1b3576698e7bbaea8aa32a2e35a1cc7f9a to address this issue. Please review @saltiniroberto

**Comment by prototypo** [comment]
Addressed Roberto's comments in https://github.com/prototypo/blockchains-in-space/commit/a4789ece7e5b74bf654e622bdbe25260dc33a0b3
